Repository 3-Musinsam/musinsam, pull requests merged in 2025-04, with the labels that each got.

#3 Feat/#1
  .gitattributes
  .gitignore
  build.gradle
  eureka-server/.gitattributes
  eureka-server/.gitignore
  eureka-server/build.gradle
  eureka-server/gradle/wrapper/gradle-wrapper.jar
  eureka-server/gradle/wrapper/gradle-wrapper.properties
  eureka-server/gradlew
  eureka-server/gradlew.bat
  eureka-server/src/main/java/com/musinsam/eurekaserver/EurekaServerApplication.java
  eureka-server/src/main/resources/application.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: enhancement

#9 [Common] 공통 모듈 초기화
  .idea/gradle.xml
  common/.gitattributes
  common/build.gradle
  common/gradle/wrapper/gradle-wrapper.jar
  common/gradle/wrapper/gradle-wrapper.properties
  common/gradlew
  common/gradlew.bat
  common/src/main/java/com/musinsam/common/CommonApplication.java
  common/src/main/resources/application.properties
  settings.gradle
Labels: enhancement

#10 [Common] 권한 확인 애너테이션 구현
  common/build.gradle
  common/src/main/java/com/musinsam/common/CommonApplication.java
  common/src/main/java/com/musinsam/common/aop/CustomPreAuthorize.java
  common/src/main/java/com/musinsam/common/aop/CustomPreAuthorizeAspect.java
  common/src/main/java/com/musinsam/common/config/AutoConfig.java
  common/src/main/java/com/musinsam/common/exception/CommonErrorCode.java
  common/src/main/java/com/musinsam/common/exception/CustomException.java
  common/src/main/java/com/musinsam/common/exception/ErrorCode.java
  common/src/main/java/com/musinsam/common/exception/ErrorResponse.java
  common/src/main/java/com/musinsam/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/musinsam/common/user/UserRoleType.java
  common/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  common/src/main/resources/application.properties
Labels: enhancement

#11 [Common] 권한과 회원 ID 자동 주입 애너테이션 구현
  common/src/main/java/com/musinsam/common/config/WebConfig.java
  common/src/main/java/com/musinsam/common/exception/CommonErrorCode.java
  common/src/main/java/com/musinsam/common/exception/ErrorCode.java
  common/src/main/java/com/musinsam/common/exception/ErrorResponse.java
  common/src/main/java/com/musinsam/common/resolver/CurrentUser.java
  common/src/main/java/com/musinsam/common/resolver/CurrentUserArgumentResolver.java
  common/src/main/java/com/musinsam/common/response/CommonResponse.java
  common/src/main/java/com/musinsam/common/response/CommonSuccessCode.java
  common/src/main/java/com/musinsam/common/response/SuccessCode.java
  common/src/main/java/com/musinsam/common/user/CurrentUserDtoApiV1.java
Labels: enhancement

#19 응답 클래스에 builder 추가
  common/src/main/java/com/musinsam/common/response/ApiResponse.java
Labels: enhancement

#20 [Order] 주문 도메인 초기 구현
  .gitignore
  build.gradle
  eureka-server/Dockerfile
  infrastructure/docker-compose.yml
  order-service/Dockerfile
  order-service/build.gradle
  order-service/src/main/java/com/musinsam/orderservice/application/dto/request/ReqOrderPatchDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/request/ReqOrderPostCancelDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/request/ReqOrderPostDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderGetByIdDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderGetDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPatchDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPostCancelDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPostDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/service/OrderServiceApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/entity/OrderEntity.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/entity/OrderItemEntity.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/vo/OrderStatus.java
  order-service/src/main/java/com/musinsam/orderservice/presentation/controller/OrderControllerApiV1.java
  order-service/src/main/resources/application.properties
  order-service/src/main/resources/application.yml
  order-service/src/main/resources/config/db.yml
  order-service/src/main/resources/config/port.yml
Labels: enhancement

#21 [Alarm] 알림 도메인 초기 구현
  alarm-service/build.gradle
  alarm-service/src/main/java/com/musinsam/alarmservice/application/dto/request/ReqAlarmPostDtoApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/application/dto/response/ResAlarmGetByIdDtoApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/application/dto/response/ResAlarmGetDtoApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/application/dto/response/ResAlarmPostDtoApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/domain/alarm/entity/AlarmEntity.java
  alarm-service/src/main/java/com/musinsam/alarmservice/presentation/controller/AlarmControllerApiV1.java
Labels: enhancement

#25 [Payment] 결제 도메인 초기 구현
  infrastructure/docker-compose.yml
  payment-service/Dockerfile
  payment-service/build.gradle
  payment-service/src/main/java/com/musinsam/paymentservice/application/dto/request/ReqPaymentPatchStatusDtoApiV1.java
  payment-service/src/main/java/com/musinsam/paymentservice/application/dto/request/ReqPaymentPostApproveDtoApiV1.java
  payment-service/src/main/java/com/musinsam/paymentservice/application/dto/request/ReqPaymentPostCancelDtoApiV1.java
  payment-service/src/main/java/com/musinsam/paymentservice/application/dto/request/ReqPaymentPostDtoApiV1.java
  payment-service/src/main/java/com/musinsam/paymentservice/application/dto/request/ReqPaymentPostInitDtoApiV1.java
  payment-service/src/main/java/com/musinsam/paymentservice/application/dto/response/ResPaymentGetByIdDtoApiV1.java
  payment-service/src/main/java/com/musinsam/paymentservice/application/dto/response/ResPaymentGetDtoApiV1.java
  payment-service/src/main/java/com/musinsam/paymentservice/application/dto/response/ResPaymentPatchStatusDtoApiV1.java
  payment-service/src/main/java/com/musinsam/paymentservice/application/dto/response/ResPaymentPostApproveDtoApiV1.java
  payment-service/src/main/java/com/musinsam/paymentservice/application/dto/response/ResPaymentPostCancelDtoApiV1.java
  payment-service/src/main/java/com/musinsam/paymentservice/application/dto/response/ResPaymentPostDtoApiV1.java
  payment-service/src/main/java/com/musinsam/paymentservice/application/dto/response/ResPaymentPostInitDtoApiV1.java
  payment-service/src/main/java/com/musinsam/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/musinsam/paymentservice/domain/payment/entity/PaymentEntity.java
  payment-service/src/main/java/com/musinsam/paymentservice/presentation/controller/PaymentControllerApiV1.java
  payment-service/src/main/resources/application.properties
  payment-service/src/main/resources/application.yml
  payment-service/src/main/resources/config/db.yml
  payment-service/src/main/resources/config/port.yml
Labels: enhancement

#30 [Ai] Ai 도메인 초기 구현
  ai-service/build.gradle
  ai-service/src/main/java/com/musinsam/aiservice/application/dto/request/ReqAiCouponPostDtoApiV1.java
  ai-service/src/main/java/com/musinsam/aiservice/application/dto/request/ReqAiOrderPostDtoApiV1.java
  ai-service/src/main/java/com/musinsam/aiservice/presentation/controller/AiController.java
  ai-service/src/main/resources/application.properties
  ai-service/src/main/resources/application.yml
Labels: enhancement

#32 [Alarm] 알림 도메인 테스트 코드 작성
  alarm-service/build.gradle
  alarm-service/src/main/resources/application.properties
  alarm-service/src/main/resources/application.yml
  alarm-service/src/test/java/com/musinsam/alarmservice/presentation/controller/AlarmControllerApiV1Test.java
  alarm-service/src/test/java/com/musinsam/alarmservice/presentation/controller/config/TestWebMvcConfig.java
Labels: enhancement

#27 [Product] 상품 도메인 초기 구현
  product-service/build.gradle
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPostApplyCouponDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPostCreateDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPutUpdateDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetCouponListDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetListDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetStockDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/entity/ProductCouponEntity.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/entity/ProductEntity.java
  product-service/src/main/java/com/musinsam/productservice/global/config/ProductResponseCode.java
  product-service/src/main/java/com/musinsam/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/main/resources/application.properties
  product-service/src/main/resources/application.yml
Labels: enhancement

#35 [Order] 주문 도메인 테스트 코드 작성
  order-service/build.gradle
  order-service/src/main/java/com/musinsam/orderservice/application/dto/request/ReqOrderPatchDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/request/ReqOrderPostCancelDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/request/ReqOrderPostDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderGetByIdDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderGetDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPatchDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPostCancelDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPostDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/presentation/controller/OrderControllerApiV1.java
  order-service/src/main/resources/application.yml
  order-service/src/main/resources/config/docs.yml
  order-service/src/test/java/com/musinsam/orderservice/presentation/controller/OrderControllerApiV1Tests.java
Labels: enhancement

#36 [Shop] 상점 도메인 초기 구현
  settings.gradle
  shop-service/.gitattributes
  shop-service/.gitignore
  shop-service/build.gradle
  shop-service/gradle/wrapper/gradle-wrapper.jar
  shop-service/gradle/wrapper/gradle-wrapper.properties
  shop-service/gradlew
  shop-service/gradlew.bat
  shop-service/settings.gradle
  shop-service/src/main/java/com/musinsam/shopservice/ShopServiceApplication.java
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/request/ReqShopPostCreateDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/request/ReqShopPostUpdateDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/response/ResShopGetDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/response/ResShopGetListDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/domain/shop/entity/ShopEntity.java
  shop-service/src/main/java/com/musinsam/shopservice/global/config/ShopResponseCode.java
  shop-service/src/main/java/com/musinsam/shopservice/presentation/controller/ShopControllerApiV1.java
  shop-service/src/main/resources/application.yml
  shop-service/src/test/java/com/musinsam/shopservice/ShopServiceApplicationTests.java
Labels: enhancement

#42 [Ai] Ai 도메인 리팩토링
  ai-service/src/main/java/com/musinsam/aiservice/AiServiceApplication.java
  ai-service/src/main/java/com/musinsam/aiservice/application/dto/request/ChatGptRequest.java
  ai-service/src/main/java/com/musinsam/aiservice/application/dto/request/ReqAiCouponPostDtoApiV1.java
  ai-service/src/main/java/com/musinsam/aiservice/application/dto/request/ReqAiOrderPostDtoApiV1.java
  ai-service/src/main/java/com/musinsam/aiservice/application/dto/response/ChatGptResponse.java
  ai-service/src/main/java/com/musinsam/aiservice/application/service/ChatGptService.java
  ai-service/src/main/java/com/musinsam/aiservice/infrastructure/client/AiClient.java
  ai-service/src/main/java/com/musinsam/aiservice/infrastructure/configuration/ChatGptConfig.java
  ai-service/src/main/java/com/musinsam/aiservice/presentation/controller/AiController.java
  ai-service/src/main/java/com/musinsam/aiservice/presentation/controller/AiControllerApiV1.java
  ai-service/src/main/resources/application.yml
Labels: refactoring

#49 [Coupon] 컨트롤러, DTO 구현 및 API 테스트 구현
  coupon-service/build.gradle
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/request/ReqCouponClaimDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/request/ReqCouponIssueDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponCancelDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponClaimDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponDeleteDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponIssueDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponUseDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponsGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/request/ReqCouponPoliciesGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/request/ReqCouponPolicyGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/request/ReqCouponPolicyIssueDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/response/ResCouponPoliciesGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/response/ResCouponPolicyGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/response/ResCouponPolicyIssueDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/entity/coupon/CouponEntity.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/entity/coupon/CouponPolicyEntity.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/vo/CouponStatus.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/vo/DiscountType.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/global/config/CouponPolicyResponseCode.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/global/config/CouponResponseCode.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponController.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponPolicyController.java
  coupon-service/src/main/resources/application-test.yml
  coupon-service/src/main/resources/application.properties
  coupon-service/src/main/resources/application.yml
  coupon-service/src/main/resources/properties/base.yml
  coupon-service/src/main/resources/properties/cloud.yml
  coupon-service/src/main/resources/properties/datasource.yml
  coupon-service/src/main/resources/properties/jpa.yml
  coupon-service/src/test/java/com/musinsam/couponservice/app/presentation/v1/CouponControllerTest.java
  coupon-service/src/test/java/com/musinsam/couponservice/app/presentation/v1/CouponPolicyControllerTest.java
  coupon-service/src/test/java/com/musinsam/couponservice/app/presentation/v1/config/TestWebMvcConfig.java
Labels: enhancement

#51 [User] 컨트롤러, DTO 구현 및 API 테스트 구현
  user-service/build.gradle
  user-service/src/main/java/com/musinsam/userservice/UserServiceApplication.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/request/ReqAuthGenerateTokenDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/request/ReqAuthLoginDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/request/ReqAuthLogoutDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/request/ReqAuthSignupDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/request/ReqAuthValidateTokenDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/response/ResAuthGenerateTokenDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/response/ResAuthLoginDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/response/ResAuthLogoutDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/response/ResAuthSignupDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/response/ResAuthValidateTokenDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/user/response/ResUserDeleteByIdDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/user/response/ResUserGetByIdDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/user/response/ResUserGetDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/user/response/ResUserPatchRoleByIdDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/domain/user/entity/UserEntity.java
  user-service/src/main/java/com/musinsam/userservice/app/domain/user/vo/UserRoleType.java
  user-service/src/main/java/com/musinsam/userservice/app/global/config/PasswordEncoderConfig.java
  user-service/src/main/java/com/musinsam/userservice/app/global/response/AuthResponseCode.java
  user-service/src/main/java/com/musinsam/userservice/app/global/response/UserResponseCode.java
  user-service/src/main/java/com/musinsam/userservice/app/presentation/v1/AuthControllerApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/presentation/v1/UserControllerApiV1.java
  user-service/src/main/resources/application-test.yml
  user-service/src/main/resources/application.properties
  user-service/src/main/resources/application.yml
  user-service/src/main/resources/properties/base.yml
  user-service/src/main/resources/properties/cloud.yml
  user-service/src/main/resources/properties/datasource.yml
  user-service/src/main/resources/properties/jpa.yml
  user-service/src/test/java/com/musinsam/userservice/app/presentation/v1/AuthControllerApiV1Test.java
  user-service/src/test/java/com/musinsam/userservice/app/presentation/v1/UserControllerApiV1Test.java
Labels: enhancement

#55 [Alarm] 알림 도메인 리팩토링
  alarm-service/build.gradle
  alarm-service/src/main/java/com/musinsam/alarmservice/AlarmServiceApplication.java
  alarm-service/src/main/java/com/musinsam/alarmservice/application/dto/request/ReqAlarmPostDtoApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/application/dto/request/SlackRequest.java
  alarm-service/src/main/java/com/musinsam/alarmservice/application/dto/response/ResAlarmGetByIdDtoApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/application/dto/response/ResAlarmGetDtoApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/application/dto/response/ResAlarmPostDtoApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/application/service/AlarmServiceApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/domain/alarm/entity/AlarmEntity.java
  alarm-service/src/main/java/com/musinsam/alarmservice/domain/alarm/repository/AlarmRepository.java
  alarm-service/src/main/java/com/musinsam/alarmservice/infrastructure/client/AiClient.java
  alarm-service/src/main/java/com/musinsam/alarmservice/infrastructure/client/SlackClient.java
  alarm-service/src/main/java/com/musinsam/alarmservice/infrastructure/exception/AlarmErrorCode.java
  alarm-service/src/main/java/com/musinsam/alarmservice/presentation/controller/AlarmControllerApiV1.java
  alarm-service/src/main/resources/application.yml
  common/src/main/java/com/musinsam/common/config/FeignConfig.java
Labels: refactoring

#57 [Order] 테스트 코드 리팩터링
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPostDtoApiV1.java
  order-service/src/test/java/com/musinsam/orderservice/presentation/controller/OrderControllerApiV1Tests.java
Labels: refactoring

#59 [User] 회원가입 구현
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/request/ReqAuthSignupDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/response/ResAuthSignupDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/service/auth/AuthService.java
  user-service/src/main/java/com/musinsam/userservice/app/application/service/auth/AuthServiceImpl.java
  user-service/src/main/java/com/musinsam/userservice/app/application/service/user/UserService.java
  user-service/src/main/java/com/musinsam/userservice/app/application/service/user/UserServiceImpl.java
  user-service/src/main/java/com/musinsam/userservice/app/domain/user/entity/UserEntity.java
  user-service/src/main/java/com/musinsam/userservice/app/domain/user/repository/auth/AuthRepository.java
  user-service/src/main/java/com/musinsam/userservice/app/domain/user/repository/user/UserRepository.java
  user-service/src/main/java/com/musinsam/userservice/app/global/response/AuthErrorCode.java
  user-service/src/main/java/com/musinsam/userservice/app/infrastructure/persistence/jpa/AuthJpaRepository.java
  user-service/src/main/java/com/musinsam/userservice/app/infrastructure/persistence/jpa/UserJpaRepository.java
  user-service/src/main/java/com/musinsam/userservice/app/presentation/v1/AuthControllerApiV1.java
  user-service/src/test/java/http/Auth-requests.http
Labels: enhancement

#62 [User] 로그인 구현
  user-service/build.gradle
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/response/ResAuthLoginDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/service/auth/AuthService.java
  user-service/src/main/java/com/musinsam/userservice/app/application/service/auth/AuthServiceImpl.java
  user-service/src/main/java/com/musinsam/userservice/app/domain/auth/jwt/JwtProvider.java
  user-service/src/main/java/com/musinsam/userservice/app/global/response/AuthErrorCode.java
  user-service/src/main/java/com/musinsam/userservice/app/infrastructure/jwt/JwtProviderImpl.java
  user-service/src/main/java/com/musinsam/userservice/app/presentation/v1/AuthControllerApiV1.java
  user-service/src/main/resources/application.yml
  user-service/src/main/resources/properties/jwt.yml
  user-service/src/main/resources/properties/redis.yml
  user-service/src/test/java/http/Auth-requests.http
Labels: enhancement

#63 [Order] 주문 엔티티 생성
  order-service/src/main/java/com/musinsam/orderservice/domain/order/entity/OrderEntity.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/entity/OrderItemEntity.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/repository/OrderRepository.java
  order-service/src/main/java/com/musinsam/orderservice/infrastructure/persistence/order/OrderJpaRepository.java
  order-service/src/main/resources/application.yml
  order-service/src/main/resources/config/jpa.yml
Labels: enhancement

#71 [User] 토큰 재발급 구현
  user-service/build.gradle
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/request/ReqAuthGenerateTokenDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/response/ResAuthGenerateTokenDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/service/auth/AuthService.java
  user-service/src/main/java/com/musinsam/userservice/app/application/service/auth/AuthServiceImpl.java
  user-service/src/main/java/com/musinsam/userservice/app/application/service/redis/RedisService.java
  user-service/src/main/java/com/musinsam/userservice/app/domain/auth/jwt/JwtProvider.java
  user-service/src/main/java/com/musinsam/userservice/app/global/response/AuthErrorCode.java
  user-service/src/main/java/com/musinsam/userservice/app/infrastructure/jwt/JwtProviderImpl.java
  user-service/src/main/java/com/musinsam/userservice/app/infrastructure/redis/config/RedisConfig.java
  user-service/src/main/java/com/musinsam/userservice/app/presentation/v1/AuthControllerApiV1.java
  user-service/src/main/resources/application.yml
  user-service/src/main/resources/properties/base.yml
  user-service/src/test/java/http/Auth-requests.http
Labels: enhancement

#73 [Common] Docker Compose Redis 추가
  infrastructure/docker-compose.yml
Labels: enhancement

#75 [Fix] application.yml 설정 변경
  infrastructure/docker-compose.yml
  order-service/src/main/resources/application.yml
  order-service/src/main/resources/config/db.yml
  order-service/src/main/resources/config/docs.yml
  order-service/src/main/resources/config/jpa.yml
  order-service/src/main/resources/config/port.yml
  payment-service/src/main/resources/application.yml
  payment-service/src/main/resources/config/db.yml
  payment-service/src/main/resources/config/docs.yml
  payment-service/src/main/resources/config/port.yml
Labels: refactoring

#78 [Event] DTO / Contoller 수정
  event-service/src/main/java/com/musinsam/eventservice/application/dto/request/ReqEventPostDtoApiV1.java
  event-service/src/main/java/com/musinsam/eventservice/application/dto/request/ReqEventPutByEventIdDtoApiV1.java
  event-service/src/main/java/com/musinsam/eventservice/application/dto/response/ResEventGetByEventIdDtoApiV1.java
  event-service/src/main/java/com/musinsam/eventservice/application/dto/response/ResEventGetDtoApiV1.java
  event-service/src/main/java/com/musinsam/eventservice/application/dto/response/ResEventGetProductByEventIdDtoApiV1.java
  event-service/src/main/java/com/musinsam/eventservice/application/dto/response/ResEventGetProductDtoApiV1.java
  event-service/src/main/java/com/musinsam/eventservice/presentation/controller/EventControllerApiV1.java
Labels: refactoring

#76 [Product] DTO / Contoller 수정
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPatchByProductIdDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPostCouponDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPostDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPutByProductIdDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetByProductIdDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetCouponDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetCouponListDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetListDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetStockDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/entity/ProductImageEntity.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/repository/ProductRepository.java
  product-service/src/main/java/com/musinsam/productservice/presentation/controller/ProductControllerApiV1.java
Labels: refactoring

#79 [User] Redis 계층 구조에 따른 수정
  user-service/src/main/java/com/musinsam/userservice/app/application/service/auth/AuthServiceImpl.java
  user-service/src/main/java/com/musinsam/userservice/app/domain/user/repository/token/RefreshTokenRepository.java
  user-service/src/main/java/com/musinsam/userservice/app/infrastructure/config/RedisConfig.java
  user-service/src/main/java/com/musinsam/userservice/app/infrastructure/redis/RefreshTokenRepositoryImpl.java
Labels: refactoring

#80 [Shop] DTO / Controller 수정
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/request/ReqShopPostDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/request/ReqShopPutByShopIdDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/response/ResShopGetByShopIdDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/response/ResShopGetCouponByShopIdDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/response/ResShopGetDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/global/config/ShopResponseCode.java
  shop-service/src/main/java/com/musinsam/shopservice/infrastructure/dto/CouponDto.java
  shop-service/src/main/java/com/musinsam/shopservice/presentation/controller/ShopControllerApiV1.java
Labels: refactoring

#84 [Common] build.gradle dependencies 수정
  common/build.gradle
Labels: wontfix

#83 [User] 로그아웃 구현
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/request/ReqAuthLogoutDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/auth/response/ResAuthLoginDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/service/auth/AuthService.java
  user-service/src/main/java/com/musinsam/userservice/app/application/service/auth/AuthServiceImpl.java
  user-service/src/main/java/com/musinsam/userservice/app/domain/auth/jwt/JwtProvider.java
  user-service/src/main/java/com/musinsam/userservice/app/domain/user/repository/token/RefreshTokenRepository.java
  user-service/src/main/java/com/musinsam/userservice/app/infrastructure/jwt/JwtProviderImpl.java
  user-service/src/main/java/com/musinsam/userservice/app/infrastructure/redis/RefreshTokenRepositoryImpl.java
  user-service/src/main/java/com/musinsam/userservice/app/presentation/v1/AuthControllerApiV1.java
  user-service/src/test/java/com/musinsam/userservice/app/presentation/v1/AuthControllerApiV1Test.java
  user-service/src/test/java/http/Auth-requests.http
Labels: enhancement

#88 [Ai] Ai 도메인 테스트코드 작성
  ai-service/build.gradle
  ai-service/src/main/java/com/musinsam/aiservice/application/dto/request/ReqAiPostDtoApiV1.java
  ai-service/src/main/java/com/musinsam/aiservice/application/service/ChatGptService.java
  ai-service/src/main/java/com/musinsam/aiservice/infrastructure/configuration/ChatGptConfig.java
  ai-service/src/main/java/com/musinsam/aiservice/presentation/controller/AiControllerApiV1.java
  ai-service/src/main/resources/application.yml
  ai-service/src/test/java/com/musinsam/aiservice/presentation/controller/AiControllerApiV1Test.java
  ai-service/src/test/java/com/musinsam/aiservice/presentation/controller/http/Ai.http
  alarm-service/src/main/java/com/musinsam/alarmservice/infrastructure/client/AiClient.java
  alarm-service/src/main/java/com/musinsam/alarmservice/presentation/controller/AlarmControllerApiV1.java
  alarm-service/src/test/java/http/Alarm.http
Labels: enhancement

#90 [Order] 주문 생성 기능 개발
  common/src/main/java/com/musinsam/common/domain/BaseEntity.java
  order-service/src/main/java/com/musinsam/orderservice/app/global/response/OrderErrorCode.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/request/ReqOrderPostDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPostDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/service/OrderServiceApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/entity/OrderEntity.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/entity/OrderItemEntity.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/repository/OrderRepository.java
  order-service/src/main/resources/application.yml
  order-service/src/test/java/com/musinsam/orderservice/presentation/controller/OrderControllerApiV1Tests.java
Labels: enhancement

#89 [Alarm] 알림 도메인 testdocs 작성
  alarm-service/build.gradle
  alarm-service/src/main/java/com/musinsam/alarmservice/presentation/controller/AlarmControllerApiV1.java
  alarm-service/src/main/resources/application.yml
  alarm-service/src/test/java/com/musinsam/alarmservice/presentation/controller/AlarmControllerApiV1Test.java
Labels: enhancement

#91 [Order] 주문 상세 조회 기능 개발
  order-service/src/main/java/com/musinsam/orderservice/application/dto/request/ReqOrderPostDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderGetByIdDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPostDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/service/OrderServiceApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/entity/OrderEntity.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/entity/OrderItemEntity.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/repository/OrderRepository.java
  order-service/src/main/java/com/musinsam/orderservice/infrastructure/persistence/order/OrderJpaRepository.java
Labels: enhancement

#92 [Order] 주문 수정 기능 개발
  order-service/src/main/java/com/musinsam/orderservice/application/dto/request/ReqOrderPatchDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/request/ReqOrderPutDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPatchDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPutDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/service/OrderServiceApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/entity/OrderEntity.java
  order-service/src/main/java/com/musinsam/orderservice/presentation/controller/OrderControllerApiV1.java
  order-service/src/test/java/com/musinsam/orderservice/presentation/controller/OrderControllerApiV1Tests.java
Labels: enhancement

#93 [Order] 주문 취소 기능 개발
  order-service/src/main/java/com/musinsam/orderservice/app/global/response/OrderErrorCode.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/request/ReqOrderPostCancelDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPostCancelDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPostDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPutDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/service/OrderServiceApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/entity/OrderEntity.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/vo/OrderCancelType.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/vo/OrderStatus.java
  order-service/src/main/java/com/musinsam/orderservice/presentation/controller/OrderControllerApiV1.java
  order-service/src/test/java/com/musinsam/orderservice/presentation/controller/OrderControllerApiV1Tests.java
Labels: enhancement

#94 [Order] 주문 삭제 기능 개발
  order-service/src/main/java/com/musinsam/orderservice/app/global/response/OrderErrorCode.java
  order-service/src/main/java/com/musinsam/orderservice/application/service/OrderServiceApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/vo/OrderStatus.java
Labels: enhancement

#96 [Order] 주문 목록 조회/검색 기능 개발
  common/build.gradle
  order-service/build.gradle
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderGetDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/service/OrderServiceApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/repository/OrderRepository.java
  order-service/src/main/java/com/musinsam/orderservice/infrastructure/config/QueryDslConfig.java
  order-service/src/main/java/com/musinsam/orderservice/infrastructure/persistence/order/OrderJpaRepository.java
  order-service/src/main/java/com/musinsam/orderservice/presentation/controller/OrderControllerApiV1.java
  order-service/src/main/resources/application.yml
Labels: enhancement

#100 [User] 회원 인증 수정 및 스웨거 설정
  eureka-gateway/build.gradle
  eureka-gateway/src/main/java/com/musinsam/eurekagateway/EurekaGatewayApplication.java
  eureka-gateway/src/main/java/com/musinsam/eurekagateway/config/AuthWhitelistProperties.java
  eureka-gateway/src/main/java/com/musinsam/eurekagateway/config/RedisConfig.java
  eureka-gateway/src/main/java/com/musinsam/eurekagateway/filter/GlobalAuthenticationFilter.java
  eureka-gateway/src/main/resources/application-local.yml
  eureka-gateway/src/main/resources/application-prod.yml
  eureka-gateway/src/main/resources/application.properties
  eureka-gateway/src/main/resources/application.yml
  eureka-gateway/src/test/java/http/user-service.http
Labels: enhancement

#101 [Product] 상품 API 테스트코드 작성
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPatchByProductIdDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPutByProductIdDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/main/resources/application.yml
  product-service/src/test/java/com/musinsam/productservice/presentation/controller/ProductControllerApiV1Test.java
Labels: enhancement

#102 [Event] 이벤트 API 테스트코드 작성
  event-service/src/main/java/com/musinsam/eventservice/presentation/controller/EventControllerApiV1.java
  event-service/src/test/java/com/musinsam/eventservice/presentation/controller/EventControllerApiV1Test.java
Labels: enhancement

#108 [Product] 상품 Entity / Repository
  product-service/build.gradle
  product-service/docker-compose.yml
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPatchByProductIdDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPostDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPutByProductIdDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetByProductIdDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetCouponDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetStockDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/entity/ProductCouponEntity.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/entity/ProductEntity.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/entity/ProductImageEntity.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/entity/ProductStatus.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/repository/ProductCouponRespository.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/repository/ProductImageRepository.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/repository/ProductRepository.java
  product-service/src/main/resources/application.yml
Labels: enhancement

#109 [Event] 이벤트 Entity / Repository
  event-service/build.gradle
  event-service/docker-compose.yml
  event-service/src/main/java/com/musinsam/eventservice/application/dto/request/ReqEventPostDtoApiV1.java
  event-service/src/main/java/com/musinsam/eventservice/application/dto/request/ReqEventPutByEventIdDtoApiV1.java
  event-service/src/main/java/com/musinsam/eventservice/application/dto/response/ResEventGetByEventIdDtoApiV1.java
  event-service/src/main/java/com/musinsam/eventservice/application/dto/response/ResEventGetDtoApiV1.java
  event-service/src/main/java/com/musinsam/eventservice/application/dto/response/ResEventGetProductByEventIdDtoApiV1.java
  event-service/src/main/java/com/musinsam/eventservice/domain/event/entity/EventEntity.java
  event-service/src/main/java/com/musinsam/eventservice/domain/event/entity/EventProductEntity.java
  event-service/src/main/java/com/musinsam/eventservice/domain/event/repository/EventProductRepository.java
  event-service/src/main/java/com/musinsam/eventservice/domain/event/repository/EventRepository.java
  event-service/src/main/resources/application.yml
Labels: enhancement

#111 [Product/Event] Swagger 설정
  event-service/build.gradle
  event-service/src/main/java/com/musinsam/eventservice/infrastructure/config/SwaggerConfig.java
  event-service/src/main/resources/application.yml
  product-service/build.gradle
  product-service/src/main/java/com/musinsam/productservice/infrastructure/config/SwaggerConfig.java
  product-service/src/main/resources/application.yml
Labels: enhancement

#112 [Ai/Alarm/Shop] Swagger 설정
  ai-service/build.gradle
  ai-service/src/main/java/com/musinsam/aiservice/infrastructure/config/ChatGptConfig.java
  ai-service/src/main/java/com/musinsam/aiservice/infrastructure/config/SwaggerConfig.java
  ai-service/src/main/resources/application.yml
  alarm-service/build.gradle
  alarm-service/src/main/java/com/musinsam/alarmservice/infrastructure/config/SwaggerConfig.java
  alarm-service/src/main/resources/application.yml
  shop-service/build.gradle
  shop-service/src/main/java/com/musinsam/shopservice/infrastructure/config/SwaggerConfig.java
Labels: enhancement

#116 [User] 회원 권한 수정
  user-service/src/main/java/com/musinsam/userservice/app/application/dto/v1/user/request/ReqUserPatchRoleByIdDtoApiV1.java
  user-service/src/main/java/com/musinsam/userservice/app/application/service/user/UserService.java
  user-service/src/main/java/com/musinsam/userservice/app/application/service/user/UserServiceImpl.java
  user-service/src/main/java/com/musinsam/userservice/app/domain/user/entity/UserEntity.java
  user-service/src/main/java/com/musinsam/userservice/app/presentation/v1/UserControllerApiV1.java
  user-service/src/test/java/http/User-requests.http
Labels: enhancement

#118 [Gateway] Body 응답 수정
  common/src/main/java/com/musinsam/common/response/ApiResponse.java
  eureka-gateway/src/main/java/com/musinsam/eurekagateway/filter/GlobalAuthenticationFilter.java
  eureka-gateway/src/main/java/com/musinsam/eurekagateway/filter/ResponseLoggingFilter.java
  eureka-gateway/src/main/resources/application.yml
Labels: enhancement

#120 [Gateway] Body 응답 수정
  common/src/main/java/com/musinsam/common/response/ApiResponse.java
Labels: refactoring

#123 [User] 회원 생성 수정 및 권한 수정
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/request/ReqCouponClaimDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/request/ReqCouponIssueDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponCancelDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponClaimDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponDeleteDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponIssueDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponUseDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponsGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/request/ReqCouponPoliciesGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/request/ReqCouponPolicyGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/request/ReqCouponPolicyIssueDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/response/ResCouponPoliciesGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/response/ResCouponPolicyGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/response/ResCouponPolicyIssueDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/couponPolicy/CouponPolicyService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/couponPolicy/CouponPolicyServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/entity/coupon/CouponEntity.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/entity/couponPolicy/CouponPolicyEntity.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/repository/couponPolicy/CouponPolicyRepository.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/vo/coupon/CouponResponseCode.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/vo/coupon/CouponStatus.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/vo/couponPolicy/CouponPolicyErrorCode.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/vo/couponPolicy/CouponPolicyResponseCode.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/vo/couponPolicy/DiscountType.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/infrastructure/persistence/jpa/couponPolicy/CouponPolicyJpaRepository.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponController.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponPolicyController.java
  coupon-service/src/test/java/com/musinsam/couponservice/app/presentation/v1/CouponPolicyControllerTest.java
Labels: refactoring

#128 [CouponPolicy] 쿠폰 정책 동적 조회
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/request/CouponPolicySearchCondition.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/couponPolicy/response/ResCouponPoliciesGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/couponPolicy/CouponPolicyService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/couponPolicy/CouponPolicyServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/repository/couponPolicy/CouponPolicyQueryRepository.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/infrastructure/config/QuerydslConfig.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/infrastructure/persistence/querydsl/CouponPolicyQueryRepositoryImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/util/querydsl/QuerydslCouponPolicySortUtil.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/util/querydsl/QuerydslUtil.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponPolicyController.java
  coupon-service/src/test/couponPolicy-reqests.http
Labels: enhancement

#130 [CouponPolicy] 쿠폰 정책 삭제
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/couponPolicy/CouponPolicyService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/couponPolicy/CouponPolicyServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/entity/couponPolicy/CouponPolicyEntity.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponPolicyController.java
  coupon-service/src/test/couponPolicy-reqests.http
Labels: enhancement

#132 [CouponPolicy] 쿠폰 정책 삭제
  eureka-gateway/src/main/resources/application.yml
Labels: refactoring

#134 [Gateway] application.yml 파일 수정
  eureka-gateway/src/main/resources/application.yml
Labels: refactoring

#136 [Gateway] ai-message 수정
  eureka-gateway/src/main/resources/application.yml
Labels: refactoring

#138 [Ai, Alarm, Shop] http 테스트코드 수정
  ai-service/src/main/java/com/musinsam/aiservice/AiServiceApplication.java
  ai-service/src/main/java/com/musinsam/aiservice/presentation/controller/AiControllerApiV1.java
  ai-service/src/main/resources/application.yml
  ai-service/src/test/java/com/musinsam/aiservice/presentation/controller/http/Ai.http
  alarm-service/src/main/java/com/musinsam/alarmservice/application/service/AlarmServiceApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/infrastructure/client/AiClient.java
  alarm-service/src/main/java/com/musinsam/alarmservice/presentation/controller/AlarmControllerApiV1.java
  alarm-service/src/main/resources/application.yml
  alarm-service/src/test/java/http/Alarm.http
  shop-service/src/main/java/com/musinsam/shopservice/application/service/ShopServiceApiV1.java
  shop-service/src/main/resources/application.yml
  shop-service/src/test/java/http/Shop.http
Labels: refactoring

#140 [Coupon] 쿠폰 발행 구현
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/request/ReqCouponIssueDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponIssueDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/couponPolicy/CouponPolicyService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/couponPolicy/CouponPolicyServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/entity/coupon/CouponEntity.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/repository/coupon/CouponRepository.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/vo/coupon/CouponErrorCode.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/vo/couponPolicy/CouponPolicyErrorCode.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/infrastructure/persistence/jpa/coupon/CouponJpaRepository.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponController.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponPolicyController.java
  coupon-service/src/test/http/coupon-requests.http
  coupon-service/src/test/http/couponPolicy-requests.http
Labels: enhancement

#147 [Product] 상품 서비스 로직
  event-service/docker-compose.yml
  product-service/build.gradle
  product-service/src/main/java/com/musinsam/productservice/ProductServiceApplication.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPostDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetByProductIdDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetCouponDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/service/impl/ProductServiceImplApiV1.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/entity/ProductEntity.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/entity/ProductImageEntity.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/repository/ProductImageRepository.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/repository/ProductRepository.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/dto/res/ResShopCouponDto.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/image/S3Folder.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/image/config/S3Config.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/image/service/FileService.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/image/service/FileServiceImpl.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/image/service/S3Service.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/image/service/S3ServiceImpl.java
  product-service/src/main/java/com/musinsam/productservice/presentation/controller/ProductControllerApiV1.java
  product-service/src/main/resources/application.yml
Labels: enhancement

#152 [Order] order.http 작성
  order-service/src/test/java/http/order.http
Labels: documentation

#154 [Payment] 결제 도메인 초기 설정
  payment-service/build.gradle
  payment-service/src/main/java/com/musinsam/paymentservice/domain/payment/entity/PaymentEntity.java
  payment-service/src/main/java/com/musinsam/paymentservice/domain/payment/vo/PaymentMethod.java
  payment-service/src/main/java/com/musinsam/paymentservice/domain/payment/vo/PaymentStatus.java
  payment-service/src/main/java/com/musinsam/paymentservice/global/response/PaymentErrorCode.java
  payment-service/src/main/java/com/musinsam/paymentservice/infrastructure/client/TossPaymentFeignClient.java
  payment-service/src/main/java/com/musinsam/paymentservice/infrastructure/config/PaymentConfig.java
  payment-service/src/main/java/com/musinsam/paymentservice/infrastructure/config/QuerydslConfig.java
  payment-service/src/main/java/com/musinsam/paymentservice/infrastructure/config/SwaggerConfig.java
  payment-service/src/main/resources/application.yml
Labels: enhancement

#159 [Payment] payment.http 작성
  payment-service/src/test/java/http/payment.http
Labels: documentation

#163 [Coupon] 쿠폰 동적 조회 구현
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/request/CouponSearchCondition.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponsGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/repository/coupon/CouponQueryRepository.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/infrastructure/persistence/querydsl/coupon/CouponQueryRepositoryImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/infrastructure/persistence/querydsl/couponPolicy/CouponPolicyQueryRepositoryImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/util/querydsl/coupon/QuerydslCouponSortUtil.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/util/querydsl/couponPolicy/QuerydslCouponPolicySortUtil.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponController.java
  coupon-service/src/test/http/coupon-requests.http
Labels: enhancement

#165 [Coupon] 단 건 쿠폰 조회
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponGetDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponController.java
  coupon-service/src/test/http/coupon-requests.http
Labels: enhancement

#167 [Coupon] 쿠폰 취소
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResCouponCancelDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponController.java
  coupon-service/src/test/http/coupon-requests.http
Labels: enhancement

#169 [Coupon] 쿠폰 삭제
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/entity/coupon/CouponEntity.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponController.java
  coupon-service/src/test/http/coupon-requests.http
Labels: enhancement

#175 [Product] 서비스 로직 수정
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetByProductIdDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/service/impl/ProductServiceImplApiV1.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/entity/ProductImageEntity.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/image/service/FileService.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/image/service/FileServiceImpl.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/s3/S3Folder.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/s3/config/S3Config.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/s3/service/S3Service.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/s3/service/S3ServiceImpl.java
  product-service/src/main/java/com/musinsam/productservice/presentation/controller/ProductControllerApiV1.java
Labels: refactoring

#174 [Gateway] 게이트웨이 수정
  eureka-gateway/src/main/resources/application.yml
Labels: enhancement

#178 [Coupon] 업체 ID로 쿠폰 목록 조회 구현
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/request/ReqShopCouponDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v1/coupon/response/ResShopCouponDtoApiV1.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/entity/coupon/CouponEntity.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/repository/coupon/CouponRepository.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/repository/couponPolicy/CouponPolicyRepository.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponInternalController.java
  coupon-service/src/test/http/coupon-requests.http
  eureka-gateway/src/main/resources/application.yml
Labels: enhancement

#179 [Product] Feign Client 통신 설정
  product-service/build.gradle
  product-service/src/main/java/com/musinsam/productservice/ProductServiceApplication.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetByProductIdDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/dto/response/ResProductGetCouponDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/integration/CouponServiceApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/integration/CouponServiceImplApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/integration/ShopServiceApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/integration/ShopServiceImplApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/client/CouponFeignClientApiV1.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/client/ShopFeignClientApiV1.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/dto/res/ResShopCouponDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/dto/res/ResShopGetByProductIdDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/presentation/controller/ProductInternalControllerApiV1.java
  product-service/src/test/java/com/musinsam/productservice/presentation/controller/ProductControllerApiV1Test.java
Labels: enhancement

#184 [Product] 재고 차감 로직 수정
  product-service/src/main/java/com/musinsam/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/entity/ProductEntity.java
Labels: refactoring

#191 [CouponPolicy] 존재하는 업체인지 확인
  common/src/main/java/com/musinsam/common/exception/CommonErrorCode.java
  common/src/main/java/com/musinsam/common/exception/CustomException.java
  coupon-service/build.gradle
  coupon-service/src/main/java/com/musinsam/couponservice/CouponServiceApplication.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/client/ShopClient.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/couponPolicy/CouponPolicyServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/vo/couponPolicy/CouponPolicyErrorCode.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/infrastructure/ShopClientImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/infrastructure/config/FeignClientConfig.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/infrastructure/config/FeignClientErrorDecoder.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/infrastructure/feign/ShopFeignClient.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponController.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponInternalController.java
Labels: enhancement

#186 [Ai/Alarm/Shop] Internal Service refactoring
  ai-service/src/main/java/com/musinsam/aiservice/presentation/controller/AiInternalControllerApiV1.java
  ai-service/src/test/java/com/musinsam/aiservice/presentation/controller/AiInternalControllerApiV1Test.java
  ai-service/src/test/java/com/musinsam/aiservice/presentation/controller/http/Ai.http
  alarm-service/src/main/java/com/musinsam/alarmservice/application/service/AlarmServiceApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/presentation/controller/AlarmControllerApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/presentation/controller/AlarmInternalControllerApiV1.java
  alarm-service/src/main/resources/application.yml
  alarm-service/src/test/java/com/musinsam/alarmservice/presentation/controller/AlarmInternalControllerApiV1Test.java
  alarm-service/src/test/java/com/musinsam/alarmservice/presentation/controller/config/TestWebMvcConfig.java
  alarm-service/src/test/java/http/Alarm.http
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/request/ReqShopGetSearchDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/response/ResShopCouponDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/response/ResShopGetCouponByShopIdDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/service/ShopServiceApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/domain/shop/repository/ShopQueryRepository.java
  shop-service/src/main/java/com/musinsam/shopservice/infrastructure/dto/CouponDto.java
  shop-service/src/main/java/com/musinsam/shopservice/infrastructure/feign/AiFeignClientApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/infrastructure/feign/CouponFeignClientApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/presentation/controller/ShopInternalControllerApiV1.java
  shop-service/src/test/java/com/musinsam/shopservice/presentation/controller/ShopInternalControllerApiV1Test.java
  shop-service/src/test/java/http/Shop.http
Labels: enhancement, refactoring

#196 [Order] 주문 도메인 리팩터링
  order-service/src/main/java/com/musinsam/orderservice/app/global/response/OrderErrorCode.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderGetByIdDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/dto/response/ResOrderPostDtoApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/service/OrderInternalServiceApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/service/OrderServiceApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/entity/OrderEntity.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/exception/OrderAccessDeniedException.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/exception/OrderControlException.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/exception/OrderCouponException.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/exception/OrderException.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/exception/OrderNotFoundException.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/exception/OrderProductException.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/exception/OrderStatusException.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/repository/OrderRepository.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/vo/OrderErrorCode.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/vo/OrderResponseCode.java
  order-service/src/main/java/com/musinsam/orderservice/infrastructure/client/dto/response/ResOrderClientGetByIdDto.java
  order-service/src/main/java/com/musinsam/orderservice/presentation/advice/OrderExceptionHandler.java
  order-service/src/main/java/com/musinsam/orderservice/presentation/controller/OrderControllerApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/presentation/controller/OrderInternalControllerApiV1.java
Labels: refactoring

#197 [Payment] 결제 도메인 리팩터링
  payment-service/src/main/java/com/musinsam/paymentservice/application/service/PaymentServiceApiV1.java
  payment-service/src/main/java/com/musinsam/paymentservice/domain/payment/exception/PaymentAccessDeniedException.java
  payment-service/src/main/java/com/musinsam/paymentservice/domain/payment/exception/PaymentControlException.java
  payment-service/src/main/java/com/musinsam/paymentservice/domain/payment/exception/PaymentException.java
  payment-service/src/main/java/com/musinsam/paymentservice/domain/payment/exception/PaymentNotFoundException.java
  payment-service/src/main/java/com/musinsam/paymentservice/domain/payment/exception/PaymentStatusException.java
  payment-service/src/main/java/com/musinsam/paymentservice/domain/payment/vo/PaymentErrorCode.java
  payment-service/src/main/java/com/musinsam/paymentservice/domain/payment/vo/PaymentMethod.java
  payment-service/src/main/java/com/musinsam/paymentservice/domain/payment/vo/PaymentResponseCode.java
  payment-service/src/main/java/com/musinsam/paymentservice/global/response/PaymentErrorCode.java
  payment-service/src/main/java/com/musinsam/paymentservice/presentation/advice/PaymentExceptionHandler.java
  payment-service/src/main/java/com/musinsam/paymentservice/presentation/controller/PaymentControllerApiV1.java
Labels: refactoring

#199 [Coupon] 수량 복구 구현
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v1/coupon/CouponServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/entity/coupon/CouponEntity.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/vo/coupon/CouponErrorCode.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v1/CouponInternalController.java
Labels: enhancement

#188 [Product] Feign Client 구조 개선
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPostDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/integration/CouponClientApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/integration/CouponServiceImplApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/integration/ShopClientApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/integration/ShopServiceApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/integration/ShopServiceImplApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/entity/ProductEntity.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/repository/ProductCouponRespository.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/repository/ProductImageRepository.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/repository/ProductRepository.java
  product-service/src/main/java/com/musinsam/productservice/domain/product/vo/ProductStatus.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/client/CouponFeignClientApiV1.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/client/ShopFeignClientApiV1.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/persistence/product/ProductImageJpaRepository.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/persistence/product/ProductJpaRepository.java
Labels: refactoring

#189 [Product] 예외처리
  product-service/src/main/java/com/musinsam/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/musinsam/productservice/global/ProductResponseCode.java
  product-service/src/main/java/com/musinsam/productservice/global/exception/ProductErrorCode.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/s3/exception/S3ErrorCode.java
  product-service/src/main/java/com/musinsam/productservice/infrastructure/s3/service/S3ServiceImpl.java
  product-service/src/main/java/com/musinsam/productservice/presentation/controller/ProductControllerApiV1.java
Labels: enhancement

#202 [Shop] 상점 조회 여부 구현
  shop-service/src/main/java/com/musinsam/shopservice/application/service/ShopInternalServiceApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/service/ShopServiceApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/presentation/controller/ShopInternalControllerApiV1.java
Labels: enhancement

#204 [Product] 상품 수정 시 이미지 수정 기능 추가
  product-service/src/main/java/com/musinsam/productservice/application/dto/request/ReqProductPutByProductIdDtoApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/service/ProductServiceApiV1.java
  product-service/src/main/java/com/musinsam/productservice/application/service/ProductServiceImplApiV1.java
  product-service/src/main/java/com/musinsam/productservice/presentation/controller/ProductControllerApiV1.java
Labels: refactoring

#207 [Coupon] V3 쿠폰 정책 생성
  coupon-service/build.gradle
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v2/coupon/request/ReqCouponIssueDtoApiV2.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v2/coupon/response/ResCouponIssueDtoApiV2.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v3/coupon/request/ReqCouponIssueDtoApiV3.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v3/coupon/response/ResCouponIssueDtoApiV3.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v3/couponPolicy/request/ReqCouponPolicyIssueDtoApiV3.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v3/couponPolicy/response/ResCouponPolicyGetDtoApiV3.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v3/couponPolicy/response/ResCouponPolicyIssueDtoApiV3.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v2/coupon/CouponService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v2/coupon/CouponServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponRedisService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponRedisServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponStateService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponStateServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/couponPolicy/CouponPolicyService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/couponPolicy/CouponPolicyServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/infrastructure/config/RedisConfig.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v2/CouponController.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v3/CouponController.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v3/CouponPolicyController.java
  coupon-service/src/main/resources/application.yml
  coupon-service/src/test/http/v3-coupon-policy-requests.http
  eureka-gateway/src/main/resources/application.yml
  infrastructure/docker-compose.yml
  infrastructure/redis-coupon-config/redis.conf
Labels: enhancement

#209 [Coupon] 모든 쿠폰 정책 조회 v3
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/couponPolicy/CouponPolicyService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/couponPolicy/CouponPolicyServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/repository/couponPolicy/CouponPolicyRepository.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v3/CouponPolicyController.java
  coupon-service/src/test/http/v3-coupon-policy-requests.http
Labels: enhancement

#211 [Common] coderabbit 추가 설정
  .coderabbit.yaml
Labels: enhancement

#214 [Order] 성능 모니터링 설정
  .gitignore
  infrastructure/docker-compose.yml
  infrastructure/grafana-dashboard/k6.json
  infrastructure/grafana/provisioning/dashboards/dashboards.yml
  infrastructure/grafana/provisioning/datasource/loki.yaml
  infrastructure/grafana/provisioning/datasource/prometheus.yaml
  infrastructure/k6-scripts/order-api-stress-test.js
  infrastructure/loki/loki-config.yaml
  infrastructure/prometheus/prometheus.yml
  order-service/build.gradle
  order-service/src/main/resources/application.yml
  payment-service/build.gradle
  payment-service/src/main/resources/application.yml
Labels: enhancement

#216 fix #215: docker-compose 수정
  infrastructure/docker-compose.yml
Labels: bug

#218 [Coupon] 쿠폰 발행 v3
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v3/coupon/request/ReqCouponIssueDtoApiV3.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v3/coupon/response/ResCouponIssueDtoApiV3.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v3/couponPolicy/response/ResCouponPolicyGetDtoApiV3.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponRedisService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponRedisServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponStateService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponStateServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/couponPolicy/CouponPolicyService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/couponPolicy/CouponPolicyServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/entity/couponPolicy/CouponPolicyEntity.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/vo/coupon/CouponErrorCode.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v3/CouponController.java
  coupon-service/src/test/http/v3-coupon-policy-requests.http
Labels: enhancement

#220 [Shop] 상점 Scheduling 적용
  alarm-service/Dockerfile
  alarm-service/build.gradle
  alarm-service/src/main/java/com/musinsam/alarmservice/infrastructure/kafka/AlarmKafkaConsumer.java
  alarm-service/src/main/resources/application.yml
  infrastructure/docker-compose.yml
  shop-service/Dockerfile
  shop-service/build.gradle
  shop-service/src/main/java/com/musinsam/shopservice/ShopServiceApplication.java
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/request/ReqAiPostDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/request/ReqAlarmPostDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/dto/response/ResAlarmPostDtoApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/application/service/ShopServiceApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/infrastructure/feign/AiFeignClientApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/infrastructure/feign/AlarmFeignClientApiV1.java
  shop-service/src/main/java/com/musinsam/shopservice/infrastructure/kafka/AlarmKafkaProducer.java
  shop-service/src/main/java/com/musinsam/shopservice/infrastructure/scheduler/WeeklyCouponBatch.java
  shop-service/src/main/java/com/musinsam/shopservice/infrastructure/scheduler/WeeklyCouponBatchImpl.java
  shop-service/src/main/java/com/musinsam/shopservice/presentation/controller/WeeklyCouponBatchControllerV1.java
  shop-service/src/main/resources/application.yml
  shop-service/src/test/java/http/Shop.http
Labels: enhancement

#223 [Coupon] 쿠폰 사용 v3
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v3/coupon/request/ReqCouponUseDtoApiV3.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v3/coupon/response/ResCouponUseDtoApiV3.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/coupon/CouponServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/entity/coupon/CouponEntity.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/domain/repository/coupon/CouponRepository.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/infrastructure/persistence/jpa/coupon/CouponJpaRepository.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v3/CouponController.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v3/CouponInternalController.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v3/CouponPolicyController.java
  coupon-service/src/test/http/v3-coupon-policy-requests.http
Labels: enhancement

#225 [Alarm] Slack 알림봇 1:1 DM 전송 서비스 구현
  alarm-service/src/main/java/com/musinsam/alarmservice/application/dto/response/SlackOpenImResponse.java
  alarm-service/src/main/java/com/musinsam/alarmservice/application/service/AlarmInternalServiceApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/application/service/SlackService.java
  alarm-service/src/main/java/com/musinsam/alarmservice/infrastructure/config/SlackFeignConfig.java
  alarm-service/src/main/java/com/musinsam/alarmservice/infrastructure/feign/SlackFeignClientApiV1.java
  alarm-service/src/main/java/com/musinsam/alarmservice/infrastructure/feign/SlackFeignClientApiV2.java
  alarm-service/src/main/java/com/musinsam/alarmservice/presentation/controller/AlarmInternalControllerApiV1.java
  alarm-service/src/main/resources/application.yml
  alarm-service/src/test/java/http/Alarm.http
Labels: enhancement

#230 [Coupon] 쿠폰 생성 및 사용 v4
  .gitignore
  coupon-service/build.gradle
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v4/coupon/request/ReqCouponIssueDtoApiV4.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v4/coupon/request/ReqCouponUseDtoApiV4.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v4/coupon/response/IssueMessage.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/dto/v4/coupon/response/ResCouponUseDtoApiV4.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v3/couponPolicy/CouponPolicyServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v4/CouponConsumer.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v4/CouponProducer.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v4/CouponService.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/application/service/v4/CouponServiceImpl.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/infrastructure/config/KafkaConfig.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v4/CouponController.java
  coupon-service/src/main/java/com/musinsam/couponservice/app/presentation/v4/CouponInternalController.java
  coupon-service/src/test/http/v3-v4-coupon-policy-requests.http
  infrastructure/docker-compose.yml
Labels: enhancement

#232 [Common] 그라파나, 프로메테우스 Coupon 설정
  infrastructure/docker-compose.yml
  infrastructure/grafana/coupon/provisioning/dashboards/coupon_service_dashboard.json
  infrastructure/grafana/coupon/provisioning/dashboards/dashboard.yml
  infrastructure/grafana/coupon/provisioning/dashboards/point_service_dashboard.json
  infrastructure/grafana/coupon/provisioning/dashboards/time_sale_service_dashboard.json
  infrastructure/grafana/coupon/provisioning/datasources/prometheus.yml
  infrastructure/prometheus/coupon/prometheus.yml
  infrastructure/prometheus/coupon/rules/coupon_alerts.yml
Labels: enhancement

#234 [Common] 그라파나, 프로메테우스 설정 수정
  coupon-service/src/main/resources/application.yml
  infrastructure/grafana/coupon/provisioning/dashboards/point_service_dashboard.json
  infrastructure/grafana/coupon/provisioning/dashboards/time_sale_service_dashboard.json
  infrastructure/prometheus/coupon/prometheus.yml
Labels: enhancement

#238 [Order] 주문 확인 요청 및 복구
  infrastructure/k6-scripts/order-api-stress-test.js
  order-service/build.gradle
  order-service/src/main/java/com/musinsam/orderservice/application/service/OrderServiceApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/exception/OrderStockRestoreException.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/repository/OrderRepository.java
  order-service/src/main/java/com/musinsam/orderservice/domain/order/vo/OrderErrorCode.java
  order-service/src/main/java/com/musinsam/orderservice/infrastructure/client/ProductFeignClient.java
  order-service/src/main/java/com/musinsam/orderservice/infrastructure/config/FeignClientConfig.java
  order-service/src/main/java/com/musinsam/orderservice/infrastructure/persistence/order/OrderJpaRepository.java
  order-service/src/main/java/com/musinsam/orderservice/presentation/advice/OrderExceptionHandler.java
  order-service/src/main/resources/application.yml
  order-service/src/test/java/http/order.http
  payment-service/src/main/java/com/musinsam/paymentservice/infrastructure/client/OrderFeignClient.java
  product-service/src/main/java/com/musinsam/productservice/presentation/controller/ProductInternalControllerApiV1.java
Labels: enhancement

#243 [Common] docker-compose.yml 수정
  infrastructure/docker-compose.yml
  shop-service/src/main/java/com/musinsam/shopservice/infrastructure/scheduler/WeeklyCouponBatch.java
Labels: enhancement, refactoring

#240 [Order] 주문 서비스 레이어 리팩토링
  order-service/src/main/java/com/musinsam/orderservice/application/service/OrderServiceApiV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/service/OrderStockManagerV1.java
  order-service/src/main/java/com/musinsam/orderservice/application/service/OrderValidatorV1.java
Labels: refactoring

#246 Update README.md
  README.md
Labels: documentation
